name: Build and publish to Docker Hub
on:
  release:
    # job will automatically run after a new "release" is create on github.
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        dry_run:
          description: 'If true, will not push the built images to docker hub.'
          required: false
          default: 'false'

jobs:
  docker_build_and_publish_opa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Get version tag from opa
        run: |
          echo "opa_version_tag=$(./scripts/get-opa-version.sh)" >> $GITHUB_ENV

      - name: Echo version tag
        run: |
          echo "The version tag that will be published to docker hub is: ${{ env.opa_version_tag }}"

      - name: Build OPA
        run: make build
        env:
          CGO_ENABLED: 0
          WASM_ENABLED: 0

      - name: Build image
        id: build_image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            BASE=gcr.io/distroless/static
          cache-from: type=registry,ref=tibotix/opa:latest-envoy-redis-static
          cache-to: type=inline
          load: true
          tags: |
            tibotix/opa:latest-envoy-redis-static
            tibotix/opa:${{ env.opa_version_tag }}-envoy-redis-static

      - name: Output local docker images
        run: docker image ls --digests | grep opa

      - name: Login to DockerHub
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true') }}
        run: docker push tibotix/opa:${{ env.opa_version_tag }}-envoy-redis-static && docker push tibotix/opa:latest-envoy-redis-static

  docker_build_and_publish_opal_client:
    runs-on: ubuntu-latest
    # needs: docker_build_and_publish_opa
    steps:
      - name: Checkout OPAL
        uses: actions/checkout@v3
        with:
          repository: permitio/opal
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version tag from git history
        run: |
          echo "opal_version_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Echo version tag
        run: |
          echo "The version tag that will be published to docker hub is: ${{ env.opal_version_tag }}"
      
      - name: Build opal-client image
        id: build_image
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: false
          target: client
          build-args: |
            opa_image=tibotix/opa
            opa_tag=latest-envoy-redis-static
          cache-from: type=registry,ref=tibotix/opal-client:latest-envoy-redis-static
          cache-to: type=inline
          load: true
          tags: |
            tibotix/opal-client:latest-envoy-redis-static
            tibotix/opal-client:${{ env.opal_version_tag }}-envoy-redis-static

      - name: Output local docker images
        run: docker image ls --digests | grep opa

      - name: Login to DockerHub
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true') }}
        run: docker push tibotix/opal-client:${{ env.opal_version_tag }}-envoy-redis-static && docker push tibotix/opal-client:latest-envoy-redis-static