name: Build and publish to Docker Hub
on:
  release:
    # job will automatically run after a new "release" is create on github.
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        dry_run:
          description: 'If true, will not push the built images to docker hub.'
          required: false
          default: 'false'

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version tag from github release
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          echo "opal_version_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Get version tag from git history
        if: ${{ !(github.event_name == 'release' && github.event.action == 'created') }}
        run: |
          echo "opal_version_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Echo version tag
        run: |
          echo "The version tag that will be published to docker hub is: ${{ env.opal_version_tag }}"

      - name: Build OPA
        run: make build
        env:
          CGO_ENABLED: 0
          WASM_ENABLED: 0

      - name: Build image
        id: build_image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          build_args: |
            BASE=gcr.io/distroless/static
          cache-from: type=registry,ref=tibotix/opa:envoy-redis-static-latest
          cache-to: type=inline
          load: true
          tags: |
            tibotix/opa:envoy-redis-static-latest
            tibotix/opa:envoy-redis-static-${{ env.opal_version_tag }}

      - name: Output local docker images
        run: docker image ls --digests | grep opa

      - name: Login to DockerHub
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push client
        if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true') }}
        run: docker push tibotix/opa:envoy-redis-static-${{ env.opal_version_tag }} && docker push tibotix/opa:envoy-redis-static-latest